import type { Product, Collection, PodcastEpisode, Program, Testimonial, FAQ } from '@/types'

export const products: Product[] = [
  {
    id: '1',
    name: 'Genesis Premium Tee',
    slug: 'genesis-premium-tee',
    price: 48,
    compareAtPrice: 65,
    description: 'Premium heavyweight cotton tee with subtle faith-inspired design. Made ethically.',
    category: 'apparel',
    images: [
      'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800',
      'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800',
      'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800',
    ],
    colors: [
      { name: 'White', hex: '#FFFFFF' },
      { name: 'Black', hex: '#000000' },
      { name: 'Sky Blue', hex: '#5bd37c' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.8,
    reviewCount: 124,
    isNew: true,
    isBestSeller: true,
    createdAt: '2025-12-01',
  },
  {
    id: '2',
    name: 'New Beginning Hoodie',
    slug: 'new-beginning-hoodie',
    price: 78,
    description: 'Oversized french terry hoodie. Stonewashed for the perfect vintage feel.',
    category: 'apparel',
    images: [
      'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800',
      'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=800',
    ],
    colors: [
      { name: 'Cream', hex: '#F5F0EB' },
      { name: 'Charcoal', hex: '#36454F' },
      { name: 'Navy', hex: '#1B2A4A' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    rating: 4.9,
    reviewCount: 89,
    isBestSeller: true,
    createdAt: '2025-11-15',
  },
  {
    id: '3',
    name: 'Faith Canvas Print',
    slug: 'faith-canvas-print',
    price: 120,
    description: 'Gallery-grade canvas print. Archival inks on textured cotton canvas.',
    category: 'artwork',
    images: [
      'https://images.unsplash.com/photo-1515405295579-ba7b454bb62b?w=800',
      'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=800',
    ],
    rating: 4.7,
    reviewCount: 56,
    isFeatured: true,
    createdAt: '2025-10-20',
  },
  {
    id: '4',
    name: 'Light Collection Cap',
    slug: 'light-collection-cap',
    price: 38,
    description: 'Premium unstructured cap. Embroidered detail, curved brim.',
    category: 'accessories',
    images: [
      'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=800',
      'https://images.unsplash.com/photo-1534215754734-18e55d13e346?w=800',
    ],
    colors: [
      { name: 'Black', hex: '#000000' },
      { name: 'Sand', hex: '#D4C5A9' },
    ],
    rating: 4.6,
    reviewCount: 43,
    isNew: true,
    createdAt: '2025-12-10',
  },
  {
    id: '5',
    name: 'Sacred Geometry Art Print',
    slug: 'sacred-geometry-art-print',
    price: 85,
    compareAtPrice: 110,
    description: 'Modern sacred geometry interpretation. Gold foil accents on premium paper.',
    category: 'artwork',
    images: [
      'https://images.unsplash.com/photo-1549887534-1541e9326640?w=800',
      'https://images.unsplash.com/photo-1549490349-8643362247b5?w=800',
    ],
    rating: 4.9,
    reviewCount: 34,
    isFeatured: true,
    createdAt: '2025-09-15',
  },
  {
    id: '6',
    name: 'Renewed Crewneck',
    slug: 'renewed-crewneck',
    price: 68,
    description: 'Brushed fleece crewneck sweater. Relaxed fit with ribbed cuffs.',
    category: 'apparel',
    images: [
      'https://images.unsplash.com/photo-1576871337622-98d48d1cf531?w=800',
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800',
    ],
    colors: [
      { name: 'Oatmeal', hex: '#E8DED1' },
      { name: 'Forest', hex: '#2D4A3E' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    rating: 4.7,
    reviewCount: 67,
    isBestSeller: true,
    createdAt: '2025-11-01',
  },
  {
    id: '7',
    name: 'Hope Tote Bag',
    slug: 'hope-tote-bag',
    price: 42,
    description: 'Heavyweight canvas tote. Reinforced stitching, interior pocket.',
    category: 'accessories',
    images: [
      'https://images.unsplash.com/photo-1544816155-12df9643f363?w=800',
      'https://images.unsplash.com/photo-1594226801341-41427b4e5c22?w=800',
    ],
    colors: [
      { name: 'Natural', hex: '#D4C5A9' },
      { name: 'Black', hex: '#000000' },
    ],
    rating: 4.5,
    reviewCount: 28,
    isNew: true,
    createdAt: '2025-12-05',
  },
  {
    id: '8',
    name: 'Limited Edition Icon Tee',
    slug: 'limited-edition-icon-tee',
    price: 55,
    description: 'Limited run artist collaboration. Premium ringspun cotton.',
    category: 'apparel',
    images: [
      'https://images.unsplash.com/photo-1529374255404-311a2a4f1fd9?w=800',
      'https://images.unsplash.com/photo-1503341455253-b2e723bb3dbb?w=800',
    ],
    colors: [
      { name: 'White', hex: '#FFFFFF' },
      { name: 'Heather Grey', hex: '#B8B8B8' },
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.8,
    reviewCount: 95,
    isNew: true,
    isFeatured: true,
    createdAt: '2025-12-15',
  },
  {
    id: '9',
    name: 'Faith in Motion Bar Necklace',
    slug: 'faith-in-motion-bar-necklace',
    price: 58,
    description: 'Minimalist bar necklace with a subtle faith-inspired design. Crafted from premium stainless steel with a polished finish.',
    category: 'accessories',
    images: [
      'https://bravo.yourwebsitedemos.com/web/Virtual-Genesis-v3/wp-content/uploads/2026/05/Outlook-bum35e3b.png',
    ],
    colors: [
      { name: 'Silver', hex: '#C0C0C0' },
      { name: 'Gold', hex: '#D4AF37' },
    ],
    rating: 4.9,
    reviewCount: 37,
    isNew: true,
    isFeatured: true,
    createdAt: '2026-01-15',
  },
  {
    id: '10',
    name: 'Faith in Motion Corded Bracelet',
    slug: 'faith-in-motion-corded-bracelet',
    price: 42,
    description: 'Handcrafted corded bracelet with faith-inspired charm. Adjustable fit with durable braided cord and premium metal accents.',
    category: 'accessories',
    images: [
      'https://bravo.yourwebsitedemos.com/web/Virtual-Genesis-v3/wp-content/uploads/2026/05/Outlook-cc45ffu1.png',
    ],
    colors: [
      { name: 'Black', hex: '#000000' },
      { name: 'Brown', hex: '#8B4513' },
    ],
    rating: 4.7,
    reviewCount: 28,
    isNew: true,
    isFeatured: true,
    createdAt: '2026-01-15',
  },
  {
    id: '11',
    name: 'Mustard Seed Mountain Necklace',
    slug: 'mustard-seed-mountain-necklace',
    price: 64,
    description: 'Inspired by the mountain-moving power of mustard seed faith. Sterling silver pendant with textured mountain detail on a fine chain.',
    category: 'accessories',
    images: [
      'https://bravo.yourwebsitedemos.com/web/Virtual-Genesis-v3/wp-content/uploads/2026/05/image1-1024x723.jpeg',
    ],
    colors: [
      { name: 'Silver', hex: '#C0C0C0' },
    ],
    rating: 4.8,
    reviewCount: 42,
    isNew: true,
    isFeatured: true,
    createdAt: '2026-01-10',
  },
]

export const collections: Collection[] = [
  {
    id: 'c1',
    name: 'Apparel',
    slug: 'apparel',
    description: 'Premium faith-inspired clothing. Designed for everyday wear.',
    image: 'https://images.unsplash.com/photo-1523381210434-271e8be1f52b?w=800',
    category: 'apparel',
    productCount: 24,
  },
  {
    id: 'c2',
    name: 'Artwork',
    slug: 'artwork',
    description: 'Modern sacred art for your space.',
    image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800',
    category: 'artwork',
    productCount: 18,
  },
  {
    id: 'c3',
    name: 'Podcast',
    slug: 'podcast',
    description: 'Conversations on faith, culture, and creativity.',
    image: 'https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=800',
    category: 'podcast',
    productCount: 0,
  },
  {
    id: 'c4',
    name: 'Coaching',
    slug: 'coaching',
    description: 'One-on-one guidance for your journey.',
    image: 'https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=800',
    category: 'coaching',
    productCount: 0,
  },
  {
    id: 'c5',
    name: 'Courses',
    slug: 'courses',
    description: 'Deep dive learning experiences.',
    image: 'https://images.unsplash.com/photo-1513258496099-48168024aec0?w=800',
    category: 'courses',
    productCount: 0,
  },
]

export const podcastEpisodes: PodcastEpisode[] = [
  {
    id: 'p1',
    title: 'New Beginnings: Finding Purpose',
    description: 'How to navigate life transitions with faith and intentionality.',
    image: 'https://images.unsplash.com/photo-1593697821014-c9301d5f0c9c?w=800',
    duration: '42:15',
    date: 'Dec 10, 2025',
    episodeNumber: 1,
    audioUrl: '#',
  },
  {
    id: 'p2',
    title: 'Creativity & Calling',
    description: 'Exploring the intersection of artistic expression and spiritual formation.',
    image: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800',
    duration: '38:42',
    date: 'Dec 3, 2025',
    episodeNumber: 2,
    audioUrl: '#',
  },
  {
    id: 'p3',
    title: 'Community in a Digital Age',
    description: 'Building authentic connections in an increasingly virtual world.',
    image: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=800',
    duration: '45:30',
    date: 'Nov 26, 2025',
    episodeNumber: 3,
    audioUrl: '#',
  },
  {
    id: 'p4',
    title: 'The Art of Stillness',
    description: 'Finding peace and clarity in a busy world through contemplative practice.',
    image: 'https://images.unsplash.com/photo-1508672019048-805c876b67e2?w=800',
    duration: '36:18',
    date: 'Nov 19, 2025',
    episodeNumber: 4,
    audioUrl: '#',
  },
]

export const programs: Program[] = [
  {
    id: 'pr1',
    title: 'Purpose Discovery',
    description: 'A 12-week journey to uncover your calling and align your life with your values.',
    image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800',
    type: 'coaching',
    price: 1200,
    sessions: 12,
    duration: '12 weeks',
    instructor: 'Sarah Mitchell',
  },
  {
    id: 'pr2',
    title: 'Faith & Finance',
    description: 'Biblical principles for financial freedom and generous living.',
    image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800',
    type: 'course',
    price: 199,
    sessions: 8,
    duration: '4 weeks',
    instructor: 'David Chen',
  },
  {
    id: 'pr3',
    title: 'Mindful Leadership',
    description: 'Lead with purpose, integrity, and emotional intelligence.',
    image: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800',
    type: 'coaching',
    price: 1800,
    sessions: 6,
    duration: '6 months',
    instructor: 'James Walker',
  },
  {
    id: 'pr4',
    title: 'Creative Worship',
    description: 'Unlock your creative potential as a form of spiritual expression.',
    image: 'https://images.unsplash.com/photo-1519892300165-cb5542fb47c7?w=800',
    type: 'course',
    price: 149,
    sessions: 6,
    duration: '3 weeks',
    instructor: 'Emily Rose',
  },
]

export const testimonials: Testimonial[] = [
  {
    id: 't1',
    name: 'Alex M.',
    role: 'Verified Buyer',
    content: 'The quality of the apparel is incredible. You can feel the difference the moment you put it on. The designs are subtle enough for daily wear but carry deep meaning.',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200',
    rating: 5,
  },
  {
    id: 't2',
    name: 'Jordan K.',
    role: 'Coaching Client',
    content: 'The coaching program transformed my perspective on what\'s possible. I went from feeling stuck to having a clear vision for my future.',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200',
    rating: 5,
  },
  {
    id: 't3',
    name: 'Taylor R.',
    role: 'Art Collector',
    content: 'The artwork speaks to my soul. Every piece in my collection from Virtual Genesis sparks conversation and contemplation.',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200',
    rating: 5,
  },
  {
    id: 't4',
    name: 'Morgan S.',
    role: 'Podcast Listener',
    content: 'Finally, a podcast that speaks to both my faith and my modern life. Every episode leaves me feeling inspired and challenged.',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200',
    rating: 5,
  },
  {
    id: 't5',
    name: 'Casey L.',
    role: 'Course Student',
    content: 'The online courses are beautifully produced and deeply substantive. Worth every penny.',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200',
    rating: 4,
  },
]

export const faqs: FAQ[] = [
  {
    id: 'f1',
    question: 'What materials do you use?',
    answer: 'We use premium, ethically sourced materials. Our apparel is primarily heavy-weight organic cotton, French terry, and recycled blends. Each piece is designed for durability and comfort.',
    category: 'products',
  },
  {
    id: 'f2',
    question: 'What is your return policy?',
    answer: 'We offer free returns within 30 days of delivery. Items must be unworn with tags attached. Artwork returns require original packaging. Start a return through your account or contact support.',
    category: 'orders',
  },
  {
    id: 'f3',
    question: 'How does coaching work?',
    answer: 'Coaching is conducted via video call. Each session is 50 minutes. You\'ll receive personalized exercises and resources between sessions. We start with a free discovery call.',
    category: 'programs',
  },
  {
    id: 'f4',
    question: 'Do you ship internationally?',
    answer: 'Yes, we ship to over 40 countries. International delivery takes 7-14 business days. Duties and taxes are calculated at checkout.',
    category: 'orders',
  },
  {
    id: 'f5',
    question: 'How are courses delivered?',
    answer: 'Courses are delivered through our learning platform with lifetime access. Each course includes video lessons, downloadable resources, and community discussion access.',
    category: 'programs',
  },
  {
    id: 'f6',
    question: 'Can I return artwork?',
    answer: 'Artwork can be returned within 14 days if damaged or not as described. Custom commissions are final sale. Contact us immediately if your artwork arrives damaged.',
    category: 'products',
  },
  {
    id: 'f7',
    question: 'What sizes do you offer?',
    answer: 'Our apparel ranges from XS to XXL. We provide detailed size guides for each product. Most items have a relaxed fit. Refer to the size chart on each product page.',
    category: 'products',
  },
  {
    id: 'f8',
    question: 'How do I access the podcast?',
    answer: 'The podcast is available on all major platforms: Apple Podcasts, Spotify, Google Podcasts, and directly on our website. New episodes release every Wednesday.',
    category: 'programs',
  },
]
